# Dockerizing MongoDB: Dockerfile for building MongoDB images
# Based on ubuntu:18.04, installs MongoDB following the instructions from:
# http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/

FROM ubuntu:18.04

# File Author / Maintainer
LABEL maintainer="Max Novelli"
LABEL mantainer_email="man8@pitt.edu"
LABEL organization="RNEL, Physical Medicine and Rehabilitation, University of Pittsburgh"
LABEL organization_website="http://rnel.pitt.edu"
LABEL image_name="mdf_mongodb_test_v1_7:2.0"
LABEL image_version="v1.7"
LABEL service="mongodb"
LABEL service_version="4.0"


# Installation:
# install gnupg2
RUN apt-get update && apt-get install -y gnupg2 wget

#
# Import MongoDB public GPG key AND create a MongoDB list file
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -

RUN echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list


# Update apt-get sources AND install MongoDB
RUN apt-get update 
RUN apt-get install -y mongodb-org

# create rnel docker group and add mongodb user to the group
RUN groupadd -g 15213 rnel-docker
RUN usermod -a -G rnel-docker mongodb

# Create the MongoDB data directory
RUN mkdir -p /mdf/mongodb/conf
RUN mkdir -p /mdf/mongodb/db
RUN chown -R root:rnel-docker /mdf/mongodb
RUN chmod -R ug+w /mdf/mongodb

# Expose port #27017 from the container to the host
EXPOSE 27017

# Set /usr/bin/mongod as the dockerized entry-point application
ENTRYPOINT ["/usr/bin/mongod"]

# volumes
VOLUME /mdf/mongodb/conf/mongod.conf
VOLUME /mdf/mongodb/db
VOLUME /mdf/mongodb/log
