function sel = chooseStartupCollections(obj)
    % create a modal window
    dh = dialog( ...
        'Position',[300 300 500 500], ...
        'Name','Collections', ...
        'Resize', 'off');
        
    th = uicontrol('Parent',dh,...
           'Style','text',...
           'Units','normalized', ...
           'Position',[0 0.9 1 0.1],...
           'String','Select collections to open at startup');
       
    sel = find(arrayfun(@(item) item.selected, obj.menu.collections));
    
    lh = uicontrol('Parent',dh,...
           'Style','list', ...
           'Max',length(obj.menu.collections), ...
           'Min',1, ...
           'Units','normalize', ...
           'Position',[0 0.1 1 0.8], ...
           'String',arrayfun(@(item) item.human_name, obj.menu.collections,'UniformOutput',0), ...
           %'Values', sel, ...
           'Callback',@mdfConfSelectCallback);
       
    bh = uicontrol('Parent',dh,...
           'Units','normalize', ...
           'Position',[0 0 1 0.1], ...
           'String','Close',...
           'Callback','delete(gcf)');
       
    % Wait for d to close before running to completion
    uiwait(dh);
   
    % call back definition
    function mdfConfSelectCallback(lh,event)
    	sel = lh.Value;
    end %function
end %function